spring.application.name=spring-boot-react-auth
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mydatabase
spring.data.mongodb.username=root
spring.data.mongodb.password=secret
spring.data.mongodb.authentication-database=admin
jwt.secret=hithisisamockauthenticationandtherforehasnoneedtobearealsecret
jwt.expiration=86400000
spring.docker.compose.enabled=false
